### ISSUE TITLE
How to activate the laser module?

### ISSUE THREAD

**Issue by apockill** [uArm-Developer/pyuf#5]
Hi, I'm trying to turn on the laser on the uArm Swift Pro using the SwiftAPI module.

How can I activate the laser?

Thanks!

**Comment by dukelec** [comment]
Sorry for late reply, because I don't receive any email notification, that's not normal.

The SwiftAPI module is not include all functionality for the arm, because I hate the commands definitions of many parts, e.g. I really don't know why there is a ``mode`` command, maybe it should be replace by name ``profile``, and only presets some parameters like acceleration. And I don't know why to use ``G0`` to disable the laser and ``G1`` to activate the laser, it should simply replaced by a parameter at end of standard ``G0`` command, which has the value range from -1 and 0 to 255, -1 mean turn off the whole laser module, include the fan, 0 to 255 otherwise set the intensity of the output with fan on.

So, all commands will be reviewed and the API and its documentation will be subject to major changes soon.
By now, you can use ``SwiftAPI.send_cmd_sync / async`` to send some G-code commands to control the laser:
1. set mode to ``Laser``: ``M2400 S1``
2. send ``G0`` command to move around the head of the arm, with laser deactivated
3. send ``G1`` command with the same parameters definition as ``G0``, but with laser activated

For example:
```
swift.send_cmd_sync('M2400 S1')
swift.send_cmd_sync('G0 X150 Y100 Z100')
swift.send_cmd_sync('G1 X150 Y-100 Z100')
```
P.S. change intensity is not support by current hardware.

**Comment by apockill** [comment]
Thanks Duke! I hope things are going well for you.
